server:
  port: 8081
  
spring:  application:    name: MEMBER-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/MemberPortalDB
  
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    service-url:      defaultZone: http://localhost:8761/eureka/
      
  instance: 
    hostname: localhost